name: ginger
description: Ginger es una aplicación destinada a ofrecer recetas, tanto de comidas como de bebidas.

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  http: ^0.12.0+1

  ## Offline
  cached_network_image: ^0.5.1

  ## Tools
  firebase_auth: ^0.8.1+4
  firebase_database: ^2.0.2
  google_sign_in: ^4.0.1+1
  intl: ^0.15.7
  package_info: ^0.4.0+1
  scoped_model: ^1.0.1
  share: ^0.6.0+1
  shared_preferences: ^0.4.0

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700

  uses-material-design: true