name: ginger
description: Ginger es una aplicación destinada a ofrecer recetas, tanto de comidas como de bebidas.

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  flutter_web_browser: ^0.10.0
  http: ^0.12.0+1

  ## Offline
  cached_network_image: ^0.7.0

  ## Tools
  flutter_picker: ^1.0.10
  intl: ^0.15.7
  package_info: ^0.4.0+1
  scoped_model: ^1.0.1
  share: ^0.6.0+1

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700

  uses-material-design: true